export const types = {
    ITEM_ADD: "ITEM_ADD",
    ITEM_DELETE: "ITEM_DELETE",
    ITEM_CHANGE: "ITEM_CHANGE",

    FORM_ADD: "FORM_ADD",
    FORM_DELETE: "FORM_DELETE",
    FORM_CHANGE: "FORM_CHANGE",
}
